version: '3.8'

services:
  high-command-ui-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: high-command-ui-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001/api
    restart: unless-stopped

networks:
  default:
    name: high-command-dev-network
